Update app-with-compose-actions.yml

diff --git a/.github/workflows/app-with-compose-actions.yml b/.github/workflows/app-with-compose-actions.yml
--- a/.github/workflows/app-with-compose-actions.yml
+++ b/.github/workflows/app-with-compose-actions.yml
@@ -1,7 +1,7 @@
 name: App With Github Actions with docker-compose CI/CD
 
 on:
-  workflow_dispatch
+  push
 
 jobs:
   ci:
@@ -17,6 +17,7 @@ jobs:
         cache: maven
     - name: Make application-prod.properties
       run: |
+        mkdir -p ./src/main/resources
         cd ./src/main/resources
         touch ./application.properties
         echo "${{ secrets.PROPERTIES }}" > ./application.properties
@@ -35,6 +36,18 @@ jobs:
       with:
         name: app
         path: ./target/*.jar
+
+    - name: Upload docker-compose.yml artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: docker-compose.yml
+        path: ./docker-compose.yml
+
+    - name: Upload Dockerfile artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: Dockerfile
+        path: ./Dockerfile
 
     - name: Login to Docker Hub
       uses: docker/login-action@v3
@@ -58,15 +71,69 @@ jobs:
     needs: ci
     runs-on: ubuntu-latest
     steps:
-    - name: Execute deployment script
-      uses: appleboy/ssh-action@v1.2.0
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ${{ secrets.EC2_USERNAME }}
-        key: ${{ secrets.EC2_PRIVATE_KEY }}
-        script: |
-            cd
-            sudo docker-compose down
-            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app-with-actions
-            sudo docker-compose up -d
-            sudo docker image prune -a -f
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: app.jar
+          path: ./app.jar
+
+      - name: Download docker-compose.yml
+        uses: actions/download-artifact@v4
+        with:
+          name: docker-compose.yml
+          path: ./docker-compose.yml
+      
+      - name: Download Dockerfile
+        uses: actions/download-artifact@v4
+        with:
+          name: Dockerfile
+          path: ./Dockerfile
+
+      - name: Execute deployment script
+        uses: appleboy/ssh-action@v1.2.0
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_PRIVATE_KEY }}
+          script: |
+              export DB_USERNAME="${{ secrets.DB_USERNAME }}"
+              export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
+              export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
+              export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
+              echo "DB_USERNAME=$DB_USERNAME"
+              echo "DB_PASSWORD=$DB_PASSWORD"
+              echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD"
+              echo "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME"
+              echo "DOCKERHUB_USERNAME{}=${DOCKERHUB_USERNAME}"
+
+              if [[ -z "$DB_USERNAME" || -z "$DB_PASSWORD" || -z "$MYSQL_ROOT_PASSWORD" ]]; then
+                echo "One or more environment variables are missing!"
+                exit 1
+              fi
+
+              if ! java -version 2>&1 | grep -q "17"; then
+                sudo apt update
+                sudo apt install -y openjdk-17-jdk
+                echo "JDK 17 installed."
+                echo 'JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"' | sudo tee -a /etc/environment
+                source /etc/environment
+                echo $JAVA_HOME
+              fi
+              if ! command -v docker &> /dev/null; then
+                echo "Installing Docker..."
+                sudo apt install -y docker.io
+                sudo systemctl start docker
+                sudo systemctl enable docker
+              fi
+              if ! command -v docker-compose &> /dev/null; then
+                echo "Installing Docker Compose..."
+                sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+                sudo chmod +x /usr/local/bin/docker-compose
+              fi
+
+              cd
+              sudo chmod +x docker-compose.yml
+              sudo docker-compose down
+              sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app-with-actions
+              sudo docker-compose up -d
+              sudo docker image prune -a -f
